### ISSUE TITLE
User interface

### ISSUE THREAD

**Issue by OeMiku** [UpVent/orchid#26]
Que sea amigable con el usuario, tengas una interfaz gráfica que te de como opcion.
Es entendible en consola, pero de manera rápido y facil tengas una interfaz gráfica con menú y todo que te permita ver la carpeta de breeds , ver tus sitios administrados y cuales estan en función y poder elegir eliminar o reemplazaar o iniciar, etc 
claro con advertencias en que si esta seguro el usuario poder realizar los cambios (los permisos )

**Comment by VentGrey** [comment]
La interfaz gráfica puede ser un componente extra de Orchid. La herramienta está pensada para servidores en producción y por lo tanto está hecha en consola. Sin embargo esto puede ser un buen acercamiento a los usuarios de escritorio que necesiten de una interfaz de manejo rápido.

**Comment by VentGrey** [comment]
El proyecto de la interfaz gráfica se llevará a cabo con el nombre de *Morningrise* [aquí](https://github.com/UpVent/Morningrise)
